### ISSUE TITLE
Admin Edit Item page not loading

### ISSUE THREAD

**Issue by lukelarsen** [nicolaslopezj/orion-admin-only-bootstrap#3]
I'm not sure if this repo is the cause but as soon as I updated this morning the edit pages of my admin stopped loading. Here is a screenshot with the console open. I wish I knew more and could help out. 
![screen shot 2015-09-21 at 9 55 56 am](https://cloud.githubusercontent.com/assets/464529/9997053/61ea3086-6047-11e5-8422-4c73d27eb5a1.png)

**Comment by lukelarsen** [comment]
I ran all the upgrades today for Meteor 1.2 and upgrades to Orion and this bug has gone away. Sorry for the false alarm.

**Comment by nicolaslopezj** [comment]
Great
